# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0 on Tue May  7 09:59:33 2024
# Model: Annual Water Yield

import logging
import sys

import natcap.invest.annual_water_yield
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/biophysical_table_gura.csv',
    'demand_table_path': '',
    'depth_to_root_rest_layer_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/depth_to_root_restricting_layer.tif',
    'eto_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/pet.tif',
    'lulc_path': '/Users/mbraaksma/Files/seals/projects/ghana_policy_forest/intermediate/stitched_lulc_simplified_scenarios/reprojected/lulc_esa_seals7_ssp5_rcp85_luh2-message_bau_2040_clipped.tif',
    'n_workers': '-1',
    'pawc_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/pawc_30s.tif',
    'precipitation_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/baseline_bio12_Annual_Precipitation.tif',
    'results_suffix': '',
    'seasonality_constant': '20',
    'sub_watersheds_path': '',
    'valuation_table_path': '',
    'watersheds_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/hybas_af_lev06_v1c.gpkg',
    'workspace_dir': '/Users/mbraaksma/Files/apec8601_project/apec8601_project/annual_water_yield',
}

if __name__ == '__main__':
    natcap.invest.annual_water_yield.execute(args)
