# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0 on Tue May  7 11:34:41 2024
# Model: Sediment Delivery Ratio

import logging
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/biophysical_table_gura.csv',
    'dem_path': '/Users/mbraaksma/Files/base_data/global_invest/nutrient_delivery/alt_m.tif',
    'drainage_path': '',
    'erodibility_path': '/Users/mbraaksma/Files/base_data/global_invest/sediment_delivery/RUSLE_KFactor_v1.1_25km.tif',
    'erosivity_path': '/Users/mbraaksma/Files/base_data/global_invest/sediment_delivery/GlobalR_NoPol-002.tif',
    'ic_0_param': '0.5',
    'k_param': '2',
    'l_max': '122',
    'lulc_path': '/Users/mbraaksma/Files/seals/projects/ghana_policy_forest/intermediate/stitched_lulc_simplified_scenarios/reprojected/lulc_esa_seals7_ssp5_rcp85_luh2-message_bau_2040_clipped.tif',
    'n_workers': '-1',
    'results_suffix': '',
    'sdr_max': '0.8',
    'threshold_flow_accumulation': '1000',
    'watersheds_path': '/Users/mbraaksma/Files/base_data/global_invest/annual_water_yield/hybas_af_lev06_v1c.gpkg',
    'workspace_dir': '/Users/mbraaksma/Files/apec8601_project/apec8601_project/nutrient_delivery',
}

if __name__ == '__main__':
    natcap.invest.sdr.sdr.execute(args)
