# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0 on Fri May  3 13:08:04 2024
# Model: Carbon Storage and Sequestration

import logging
import sys

import natcap.invest.carbon
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'calc_sequestration': False,
    'carbon_pools_path': '/Users/mbraaksma/Files/apec8601_project/apec8601_project/base_data/invest/carbon/seals_biophysical_table.csv',
    'discount_rate': '',
    'do_redd': False,
    'do_valuation': False,
    'lulc_cur_path': '/Users/mbraaksma/Files/seals/projects/ghana_policy/reproj/lulc_esa_seals7_ssp5_rcp85_luh2-message_bau_2075_clipped_reproj.tif',
    'lulc_cur_year': '',
    'lulc_fut_path': '',
    'lulc_fut_year': '',
    'lulc_redd_path': '',
    'n_workers': '-1',
    'price_per_metric_ton_of_c': '',
    'rate_change': '',
    'results_suffix': '',
    'workspace_dir': '/Users/mbraaksma/Files/apec8601_project/apec8601_project/invest/carbon',
}

if __name__ == '__main__':
    natcap.invest.carbon.execute(args)
